### ISSUE TITLE
`selectedDate` should skip to next month when reaching the end of the current month

### ISSUE THREAD

**Issue by jeromegn** [glad/glDatePicker#11] opened 2012-05-31 20:32 UTC
**Expected:** Selected date upon showing the calendar shows the next month if the `selectedDate` settings + the current date is more than the current month's last date.

**Actual:** Current month is shown, last day is selected.

glDatePicker should be aware of the last dates of each month (watch out for February there!) and skip to the next month if the `selectedDate` setting is higher than the remaining days of the current month.

**Comment by glad** [comment] 2012-07-26 23:58
This will be resolved in the next update.  Clicking on a date that is on the previous or next month will switch the calendar to that month.

**Comment by bekken** [comment] 2012-07-27 09:41
jeromegn: I was just looking for the same fix because setting an date with .selectedDate only works if it is within the current month for today. A little bit of trial and error and I have a quick and dirty solution that works for my project.

Add:
if (selectedDate.getMonth()) {theDate = selectedDate;}

After:
// Get the current date to render
var theDate = target.data("theDate");
theDate = (theDate == -1 || typeof theDate == "undefined") ? startDate : theDate;

Can not say the exact line-number because I changed some stuff to work with swedish language.

**Comment by glad** [comment] 2012-07-27 11:18
The issue with my implementation was that I simply looked at the cell being clicked on and got the text part of it assuming it is all from the same month.  The new implementation actually stores the date in each cell (in data()) making it easier to retrieve the actual date on click.

**Comment by glad** [comment] 2012-12-23 21:55
Duplicate of: https://github.com/glad/glDatePicker/issues/12#issuecomment-11651013

**Closed as completed by glad** 2012-12-23 21:55 UTC
